### ISSUE TITLE
[InititalSetup] Make configuration changes to integrate Firebase framework

### ISSUE THREAD

**Issue by Arshir** [BuildForSDG/Team-203-TranSafe#3]
**Problem**
Firebase is require in developing the backend of the project

**TODO**
Make code and filesystem changes to integrate Firebase framework in the repository

**Comment by mickeymond** [comment]
@Arshir Please assign this task to @ian0549 because the Angular/Ionic project going to use a high-level firebase SDK like **AngularFire** or even better. So @ian0549 is the best person to add this to the project.

**Comment by mickeymond** [comment]
@Arshir Can this issue be closed?

**Comment by Arshir** [comment]
Alright @mickeymond

**Comment by Arshir** [comment]
@ian0549 if this is done kindly close it.
