### ISSUE TITLE
[FEATURE] UI User profile page

### ISSUE THREAD

**Issue by Arshir** [BuildForSDG/Team-203-TranSafe#52]
**Is your feature request related to a problem? Please describe.**
Display username, photo, phone, RiskLevel in the profile page

**Describe the solution you'd like**
Show a username ,photo, phone, RiskLevel in the user profile page

**Describe alternatives you've considered**

**Additional context**

**Comment by ErnestinaTawiah** [comment]
mail acknowledged

Best,
Tina
