### ISSUE TITLE
API endpoint to compute and store user over speeding

### ISSUE THREAD

**Issue by Arshir** [BuildForSDG/Team-203-TranSafe#7]
**Is your feature request related to a problem? Please describe.**
Real time check of user over-speeding violation

**Describe the solution you'd like**
Calculate user over speeding based on user speed and speed limit at current location. Kindly refer to the milestone of this issue for more information about speed limit.f The record should include details : Speed limit, Actual speed, Date and Time, Location, Location Type, Duration of over speeding lasted.

**Describe alternatives you've considered**

**Additional context**
Steps: 
1. Determine the type of place for the current location of the user's device from the google map api
2. Determine if the type of place in step 1 is either an Urban area, or Highway or Motor way
3. If type of place is e.g Urban then use the speed limit as prescribed in the milestone description
4. Get the current speed from the google map api.
5. Based on the current speed and the speed limit , calculate over speeding where current speed > prescribed speed limit for the location type.
6. Save the over speeding to database together with date , time , GPS location , User id.

Please let me know if any challenge.

**Comment by mickeymond** [comment]
Since we are going to use Cloud Functions to serve the API purposes, can we rename this issue to 

> cloud function to ...
